"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 6.0
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-0q358j@g8!mch-=l435xtm&@9wnjrd+sr9v@9vrd^5h4+ypq2)'

DEBUG = True


# 🔥 VERY IMPORTANT
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
]


# -------------------- APPLICATIONS --------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third party
    'rest_framework',
    'corsheaders',

    # local app
    'app',
]


# -------------------- MIDDLEWARE --------------------
# ⚠️ ORDER MATTERS – CorsMiddleware MUST be first

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# -------------------- CORS & CSRF (ANGULAR FIX) --------------------

# 🔥 DEVELOPMENT ONLY
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:4200",
]


# -------------------- URL CONFIG --------------------

ROOT_URLCONF = 'backend.urls'


# -------------------- TEMPLATES --------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# -------------------- WSGI --------------------

WSGI_APPLICATION = 'backend.wsgi.application'


# -------------------- DATABASE --------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pythonbatch02',
        'USER': 'root',
        'PASSWORD': 'system',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}


# -------------------- PASSWORD VALIDATION --------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# -------------------- INTERNATIONALIZATION --------------------

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# -------------------- STATIC FILES --------------------

STATIC_URL = 'static/'


# -------------------- DEFAULT PRIMARY KEY --------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
